# UBKGBox Docker Compose file
name: ubkgbox

services:

  # ubkg-front-end hosts clients that query the UBKG neo4j back end.

  ubkg-front-end:
    # Use the published image and tag from Docker Hub
    image: hubmap/ubkg-front-end:latest

    # Map host machine port 7000 to container port 8080
    # Only root can listen on ports below 1024, we use higher-numbered ports
    # since nginx is running under non-root user ubkg.
    # Divergence from standard hubmapconsortium API architecture:
    # The standard architecture maps port 6666, which the Chrome browser considers an "unsafe port".
    ports:
      - "7000:8080"
    volumes:
      # Mount the ubkg-api's app config (in the instance subdirectory of the build directory) to container in order to keep it outside of the image.
      - "./api_instance:/usr/src/app/src/ubkg_api/instance"
      # Mount the nginx log to container
      - "./log:/usr/src/app/log"

    environment:
      # UID and GID 1001 to match the ubkg user by default.
      # These environment variables will be passed to the Dockerfile and used to configure the non-root
      # user under which nginx will run.
      - HOST_GID=${HOST_GID:-1001}
      - HOST_UID=${HOST_UID:-1001}

    mem_limit: 2g # Limit to 2GB of RAM

    # Wait until the neo4j server in the back end service is running.
    depends_on:
      ubkg-back-end:
        condition: service_healthy

  # ubkg-back-end will be based on a local turnkey distribution of a Docker container. 
  ubkg-back-end:
    # Use the published image and tag from Docker Hub which is used to build the turnkey Docker distribution
    image: hubmap/ubkg-neo4j:current-release

    # Map host machine ports to container ports, as defined in the container.cfg file for the back end.
    ports:
      # ui port
      - ${UI_PORT}:7474
      # bolt port
      - ${BOLT_PORT}:7687

    # Map to the external bind mounts.
    volumes:
      # neo4j database
      - "./data:/usr/src/app/neo4j/data"
      # logs
      - "./logs:/usr/src/app/neo4j/logs"

    environment:
      # neo4j username and password obtained by the build_ubkgbox.sh script from container.cfg.
      - NEO4J_USER
      - NEO4J_PASSWORD

    mem_limit: 2g 

    # Check that the neo4j service is running in the container. The startup process takes some time; in addition, it stops and starts
    # the neo4j server. Wait at least 30 s before starting the health check.
    healthcheck:
      test: [ "CMD", "/usr/src/app/neo4j/bin/cypher-shell", "-u", "neo4j", "-p", "${NEO4J_PASSWORD}", "MATCH () RETURN count(*) as count" ]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 30s



    