version: '3.7'
# https://docs.docker.com/compose/compose-file/compose-file-v3/

services:
  ubkg-neo4j:
    container_name: ubkg-neo4j
    build: neo4j
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ubkg-neo4j-data:/data
    healthcheck:
      # https://docs.docker.com/engine/reference/builder/#healthcheck
      test: ["CMD", "curl", "--fail", "http://localhost:7474/", "||", "exit 1"]
      # test: curl --fail -s http://localhost:7474/ || exit 1
      # test: perl -MIO::Socket::INET -e 'exit(! defined( IO::Socket::INET->new("localhost:7687")))'
      interval: 10s
      timeout: 10s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 8G
    # Allow the JVM to read cgroup limits
    # -XX:+UseContainerSupport is enabled by default on linux machines,
    # this feature was introduced in java10 then backported to Java-8u191, the base image comes with OpenJDK(build 1.8.0_232-b09)
    # -XX:MaxRAMPercentage (double) is depending on the max memory limit assigned to the contaienr
    # When the container has > 1G memory, set -XX:MaxRAMPercentage=75.0 is good (doesn't waste too many resources)
    environment:
      - NEO4J_USER=${NEO4J_USER:-neo4j}
      # Used for setting the initial neo4j password, defaut to HappyG0at
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-HappyG0at}
      # Allow the JVM to read cgroup limits
      # -XX:+UseContainerSupport is enabled by default on linux machines,
      # this feature was introduced in java10 then backported to Java-8u191, the base image comes with OpenJDK(build 1.8.0_232-b09)
      # -XX:MaxRAMPercentage (double) is depending on the max memory limit assigned to the contaienr
      # When the container has > 1G memory, set -XX:MaxRAMPercentage=75.0 is good (doesn't waste too many resources)
      - _JAVA_OPTIONS=-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0

  ubkg-api:
    container_name: ubkg-api
    build: api
    restart: unless-stopped
    environment:
      - HOST_GID=${HOST_GID:-1000}
      - HOST_UID=${HOST_UID:-1000}
    volumes:
      # Persist the logging
      - "./api/log:/usr/src/app/log"
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
      - 8080:8080

volumes:
  ubkg-neo4j-data:

